-- Pre-rendered, sanitised HTML for each job description.
-- Generated by the per-vendor HeuristicDescriptionFormatter so the
-- frontend can drop it straight into the DOM via dangerouslySetInnerHTML.
ALTER TABLE jobs
    ADD COLUMN description_html TEXT;
