-- Augmented seed: well-known UAE organisations that hire for IT / tech roles.
-- This complements V18 (which seeds from companies present in our jobs table)
-- with anchor brands across banks, telecom, aviation, e-commerce, government,
-- energy, healthcare, real estate, consulting, recruitment, and MNCs.
--
-- Source: hand-curated from operator knowledge + WebSearch verification (June
-- 2026). For each row, careers_url is either a verified live careers page or
-- the company's main domain (in which case url_verified = false, so the admin
-- queue surfaces them for human verification).
--
-- All rows inserted with status = APPROVED so the public directory is
-- populated immediately. ON CONFLICT (slug) DO NOTHING means V18 wins for any
-- name collision — scraper-derived rows have richer signal (real apply_url +
-- emirate + category) than this hand-curated set.

INSERT INTO hiring_companies (
    name, slug, category, city, careers_url, website_url,
    hiring_status, status, url_verified, featured, created_at, updated_at
) VALUES
    -- ── Banking & FinTech ──────────────────────────────────────────────
    ('First Abu Dhabi Bank (FAB)', 'first-abu-dhabi-bank-fab', 'Banking & FinTech', 'Abu Dhabi',
     'https://www.bankfab.com/en-ae/about-fab/careers',
     'https://www.bankfab.com/', 'ACTIVE_HIRING', 'APPROVED', true, true, now(), now()),
    ('Emirates NBD', 'emirates-nbd', 'Banking & FinTech', 'Dubai',
     'https://www.emiratesnbd.com/en/careers',
     'https://www.emiratesnbd.com/', 'ACTIVE_HIRING', 'APPROVED', true, true, now(), now()),
    ('Abu Dhabi Commercial Bank (ADCB)', 'abu-dhabi-commercial-bank-adcb', 'Banking & FinTech', 'Abu Dhabi',
     'https://adcbcareers.com/',
     'https://www.adcb.com/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Mashreq', 'mashreq', 'Banking & FinTech', 'Dubai',
     'https://www.mashreq.com/en/uae/about-us/careers/careers-portal',
     'https://www.mashreq.com/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Dubai Islamic Bank (DIB)', 'dubai-islamic-bank-dib', 'Banking & FinTech', 'Dubai',
     'https://careers.dib.ae/',
     'https://www.dib.ae/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Abu Dhabi Islamic Bank (ADIB)', 'abu-dhabi-islamic-bank-adib', 'Banking & FinTech', 'Abu Dhabi',
     'https://www.adib.ae/en/pages/careers.aspx',
     'https://www.adib.ae/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('RAKBANK', 'rakbank', 'Banking & FinTech', 'Ras Al Khaimah',
     'https://careers.rakbank.ae/',
     'https://www.rakbank.ae/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Commercial Bank of Dubai (CBD)', 'commercial-bank-of-dubai-cbd', 'Banking & FinTech', 'Dubai',
     'https://www.cbd.ae/general/careers',
     'https://www.cbd.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Wio Bank', 'wio-bank', 'Banking & FinTech', 'Abu Dhabi',
     'https://www.wio.io/careers',
     'https://www.wio.io/', 'ACTIVE_HIRING', 'APPROVED', false, true, now(), now()),
    ('Tabby', 'tabby', 'Banking & FinTech', 'Dubai',
     'https://tabby.ai/careers',
     'https://tabby.ai/', 'ACTIVE_HIRING', 'APPROVED', false, true, now(), now()),
    ('Tamara', 'tamara', 'Banking & FinTech', 'Dubai',
     'https://tamara.co/careers',
     'https://tamara.co/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),

    -- ── Telecom ────────────────────────────────────────────────────────
    ('e& (Etisalat Group)', 'e-and-etisalat-group', 'Telecom', 'Abu Dhabi',
     'https://careers.etisalat.ae/',
     'https://www.eand.com/', 'ACTIVE_HIRING', 'APPROVED', true, true, now(), now()),
    ('du', 'du', 'Telecom', 'Dubai',
     'https://www.du.ae/about-us/careers',
     'https://www.du.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),

    -- ── Aviation & Travel ──────────────────────────────────────────────
    ('Emirates Group', 'emirates-group', 'Aviation & Travel', 'Dubai',
     'https://www.emiratesgroupcareers.com/',
     'https://www.emirates.com/', 'ACTIVE_HIRING', 'APPROVED', true, true, now(), now()),
    ('Etihad Airways', 'etihad-airways', 'Aviation & Travel', 'Abu Dhabi',
     'https://careers.etihad.com/',
     'https://www.etihad.com/', 'FREQUENT_HIRING', 'APPROVED', true, true, now(), now()),
    ('flydubai', 'flydubai', 'Aviation & Travel', 'Dubai',
     'https://www.flydubai.com/en/about/careers',
     'https://www.flydubai.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Air Arabia', 'air-arabia', 'Aviation & Travel', 'Sharjah',
     'https://www.airarabia.com/en/careers',
     'https://www.airarabia.com/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('Dubai Airports', 'dubai-airports', 'Aviation & Travel', 'Dubai',
     'https://www.dubaiairports.ae/careers',
     'https://www.dubaiairports.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),

    -- ── AI & Technology (G42 ecosystem + more) ─────────────────────────
    ('G42', 'g42', 'AI & Technology', 'Abu Dhabi',
     'https://careers.g42.ai/',
     'https://www.g42.ai/', 'ACTIVE_HIRING', 'APPROVED', true, true, now(), now()),
    ('Core42', 'core42', 'AI & Technology', 'Abu Dhabi',
     'https://careers.g42.ai/',
     'https://www.core42.ai/', 'ACTIVE_HIRING', 'APPROVED', true, false, now(), now()),
    ('Presight', 'presight', 'AI & Technology', 'Abu Dhabi',
     'https://careers.g42.ai/',
     'https://www.presight.ai/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('CPX', 'cpx', 'Cybersecurity', 'Abu Dhabi',
     'https://careers.g42.ai/',
     'https://www.cpx.net/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Inception (G42)', 'inception-g42', 'AI & Technology', 'Abu Dhabi',
     'https://careers.g42.ai/',
     'https://www.inceptioniai.org/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Injazat', 'injazat', 'AI & Technology', 'Abu Dhabi',
     'https://www.injazat.com/careers',
     'https://www.injazat.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),

    -- ── E-commerce & Marketplaces ──────────────────────────────────────
    ('Careem', 'careem', 'E-commerce & Marketplace', 'Dubai',
     'https://careers.careem.com/',
     'https://www.careem.com/', 'ACTIVE_HIRING', 'APPROVED', false, true, now(), now()),
    ('Talabat', 'talabat', 'E-commerce & Marketplace', 'Dubai',
     'https://careers.talabat.com/',
     'https://www.talabat.com/', 'ACTIVE_HIRING', 'APPROVED', false, true, now(), now()),
    ('Noon', 'noon', 'E-commerce & Marketplace', 'Dubai',
     'https://careers.noon.com/',
     'https://www.noon.com/', 'FREQUENT_HIRING', 'APPROVED', false, true, now(), now()),
    ('Dubizzle Group', 'dubizzle-group', 'E-commerce & Marketplace', 'Dubai',
     'https://careers.dubizzle.com/',
     'https://www.dubizzle.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Bayut', 'bayut', 'Real Estate', 'Dubai',
     'https://careers.dubizzle.com/',
     'https://www.bayut.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Property Finder', 'property-finder', 'Real Estate', 'Dubai',
     'https://www.propertyfinder.com/career',
     'https://www.propertyfinder.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Kitopi', 'kitopi', 'E-commerce & Marketplace', 'Dubai',
     'https://kitopi.com/careers/',
     'https://kitopi.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),

    -- ── Logistics ──────────────────────────────────────────────────────
    ('DP World', 'dp-world', 'Logistics', 'Dubai',
     'https://careers.dpworld.com/',
     'https://www.dpworld.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Aramex', 'aramex', 'Logistics', 'Dubai',
     'https://www.aramex.com/about-us/careers',
     'https://www.aramex.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Emirates Post', 'emirates-post', 'Logistics', 'Dubai',
     'https://www.epg.gov.ae/en/careers',
     'https://www.epg.gov.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),

    -- ── Government & Smart Cities ──────────────────────────────────────
    ('Telecommunications & Digital Government Regulatory Authority (TDRA)', 'tdra',
     'Government & Smart Cities', 'Abu Dhabi',
     'https://careers.tdra.gov.ae/',
     'https://tdra.gov.ae/', 'OCCASIONAL', 'APPROVED', true, false, now(), now()),
    ('Digital Dubai Authority', 'digital-dubai-authority', 'Government & Smart Cities', 'Dubai',
     'https://dubaicareers.ae/',
     'https://www.digitaldubai.ae/', 'OCCASIONAL', 'APPROVED', true, false, now(), now()),
    ('Hub71', 'hub71', 'AI & Technology', 'Abu Dhabi',
     'https://jobs.hub71.com/jobs',
     'https://www.hub71.com/', 'ACTIVE_HIRING', 'APPROVED', true, true, now(), now()),
    ('Dubai Future Foundation', 'dubai-future-foundation', 'Government & Smart Cities', 'Dubai',
     'https://www.dubaifuture.ae/',
     'https://www.dubaifuture.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('Smart Dubai', 'smart-dubai', 'Government & Smart Cities', 'Dubai',
     'https://dubaicareers.ae/',
     'https://www.digitaldubai.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),

    -- ── Energy & Utilities ─────────────────────────────────────────────
    ('ADNOC', 'adnoc', 'Energy & Utilities', 'Abu Dhabi',
     'https://careers.adnoc.ae/',
     'https://www.adnoc.ae/', 'ACTIVE_HIRING', 'APPROVED', false, false, now(), now()),
    ('ENOC', 'enoc', 'Energy & Utilities', 'Dubai',
     'https://www.enoc.com/en/careers',
     'https://www.enoc.com/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('TAQA', 'taqa', 'Energy & Utilities', 'Abu Dhabi',
     'https://www.taqa.com/careers/',
     'https://www.taqa.com/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('DEWA', 'dewa', 'Energy & Utilities', 'Dubai',
     'https://www.dewa.gov.ae/en/about-us/careers',
     'https://www.dewa.gov.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),

    -- ── Healthcare ─────────────────────────────────────────────────────
    ('SEHA', 'seha', 'Healthcare', 'Abu Dhabi',
     'https://www.seha.ae/careers',
     'https://www.seha.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('PureHealth', 'purehealth', 'Healthcare', 'Abu Dhabi',
     'https://www.purehealth.ae/careers',
     'https://www.purehealth.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('Aster DM Healthcare', 'aster-dm-healthcare', 'Healthcare', 'Dubai',
     'https://www.asterdmhealthcare.com/careers',
     'https://www.asterdmhealthcare.com/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('Mediclinic Middle East', 'mediclinic-middle-east', 'Healthcare', 'Dubai',
     'https://www.mediclinic.ae/en/corporate/careers.html',
     'https://www.mediclinic.ae/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),

    -- ── Real Estate & Conglomerates ────────────────────────────────────
    ('Emaar', 'emaar', 'Real Estate', 'Dubai',
     'https://careers.emaar.com/',
     'https://www.emaar.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Majid Al Futtaim', 'majid-al-futtaim', 'Real Estate', 'Dubai',
     'https://www.majidalfuttaim.com/en/careers/discover-careers-at-maf',
     'https://www.majidalfuttaim.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Al Futtaim Group', 'al-futtaim-group', 'Real Estate', 'Dubai',
     'https://www.alfuttaimcareers.com/',
     'https://www.alfuttaim.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Dubai Holding', 'dubai-holding', 'Real Estate', 'Dubai',
     'https://careers.dubaiholding.com/',
     'https://www.dubaiholding.com/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('Damac Properties', 'damac-properties', 'Real Estate', 'Dubai',
     'https://www.damacgroup.com/en/careers/',
     'https://www.damacproperties.com/', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),

    -- ── Consulting & Big 4 ─────────────────────────────────────────────
    ('Accenture Middle East', 'accenture-middle-east', 'Consulting & Services', 'Dubai',
     'https://www.accenture.com/ae-en/careers',
     'https://www.accenture.com/ae-en', 'ACTIVE_HIRING', 'APPROVED', false, false, now(), now()),
    ('Deloitte Middle East', 'deloitte-middle-east', 'Consulting & Services', 'Dubai',
     'https://www2.deloitte.com/xe/en/pages/careers/articles/careers-in-the-middle-east.html',
     'https://www2.deloitte.com/xe/en.html', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('PwC Middle East', 'pwc-middle-east', 'Consulting & Services', 'Dubai',
     'https://www.pwc.com/m1/en/careers.html',
     'https://www.pwc.com/m1/en.html', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('EY Middle East', 'ey-middle-east', 'Consulting & Services', 'Dubai',
     'https://www.ey.com/en_ae/careers',
     'https://www.ey.com/en_ae', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('KPMG Lower Gulf', 'kpmg-lower-gulf', 'Consulting & Services', 'Dubai',
     'https://kpmg.com/ae/en/home/careers.html',
     'https://kpmg.com/ae/en/home.html', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),

    -- ── MNC Tech in UAE ───────────────────────────────────────────────
    ('Microsoft (UAE)', 'microsoft-uae', 'Enterprise IT', 'Dubai',
     'https://careers.microsoft.com/v2/global/en/locations/united-arab-emirates',
     'https://www.microsoft.com/en-ae', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Google Cloud (UAE)', 'google-cloud-uae', 'Enterprise IT', 'Dubai',
     'https://www.google.com/about/careers/applications/jobs/results/?location=United+Arab+Emirates',
     'https://about.google/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Amazon Web Services (UAE)', 'amazon-web-services-uae', 'Cloud & DevOps', 'Dubai',
     'https://www.amazon.jobs/en/locations/united-arab-emirates',
     'https://aws.amazon.com/', 'FREQUENT_HIRING', 'APPROVED', true, false, now(), now()),
    ('Oracle (UAE)', 'oracle-uae', 'Enterprise IT', 'Dubai',
     'https://careers.oracle.com/jobs/#en/sites/jobsearch/locations/300000000148927',
     'https://www.oracle.com/ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('SAP (UAE)', 'sap-uae', 'Enterprise IT', 'Dubai',
     'https://jobs.sap.com/search/?locationsearch=United%20Arab%20Emirates',
     'https://www.sap.com/uae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('IBM (UAE)', 'ibm-uae', 'Enterprise IT', 'Dubai',
     'https://www.ibm.com/careers/search?field_keyword_18%5B0%5D=United%20Arab%20Emirates',
     'https://www.ibm.com/ae-en', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Cisco (UAE)', 'cisco-uae', 'Enterprise IT', 'Dubai',
     'https://jobs.cisco.com/jobs/SearchJobs/?listFilterMode=1&21178=%5B186065%5D',
     'https://www.cisco.com/c/en_ae/index.html', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),
    ('Dell Technologies (UAE)', 'dell-technologies-uae', 'Enterprise IT', 'Dubai',
     'https://jobs.dell.com/',
     'https://www.dell.com/en-ae', 'OCCASIONAL', 'APPROVED', false, false, now(), now()),

    -- ── Recruitment Agencies (specialist tech) ─────────────────────────
    ('Halian', 'halian', 'Recruitment & Staffing', 'Dubai',
     'https://www.halian.com/en-ae/',
     'https://www.halian.com/', 'ACTIVE_HIRING', 'APPROVED', true, false, now(), now()),
    ('Marc Ellis', 'marc-ellis', 'Recruitment & Staffing', 'Dubai',
     'https://www.marc-ellis.com/',
     'https://www.marc-ellis.com/', 'ACTIVE_HIRING', 'APPROVED', true, false, now(), now()),
    ('Cooper Fitch', 'cooper-fitch', 'Recruitment & Staffing', 'Dubai',
     'https://cooperfitch.ae/',
     'https://cooperfitch.ae/', 'ACTIVE_HIRING', 'APPROVED', true, false, now(), now()),
    ('Charterhouse Middle East', 'charterhouse-middle-east', 'Recruitment & Staffing', 'Dubai',
     'https://www.charterhouseme.ae/',
     'https://www.charterhouseme.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Black Pearl Consulting', 'black-pearl-consulting', 'Recruitment & Staffing', 'Dubai',
     'https://www.blackpearlconsult.com/',
     'https://www.blackpearlconsult.com/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Michael Page Middle East', 'michael-page-middle-east', 'Recruitment & Staffing', 'Dubai',
     'https://www.michaelpage.ae/',
     'https://www.michaelpage.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Robert Half Middle East', 'robert-half-middle-east', 'Recruitment & Staffing', 'Dubai',
     'https://www.roberthalf.ae/',
     'https://www.roberthalf.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Hays Middle East', 'hays-middle-east', 'Recruitment & Staffing', 'Dubai',
     'https://www.hays.ae/',
     'https://www.hays.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now()),
    ('Adecco Middle East', 'adecco-middle-east', 'Recruitment & Staffing', 'Dubai',
     'https://www.adecco.ae/',
     'https://www.adecco.ae/', 'FREQUENT_HIRING', 'APPROVED', false, false, now(), now())
ON CONFLICT (slug) DO NOTHING;
